version: 2.1
orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install dependencies
          command: pip install .[test]
      - run:
          name: Run tests
          command: python -m pytest

workflows:
  main:
    jobs:
      - python/test:
          args: '--dev'
          pkg-manager: pip
          test-tool: pytest
      - build-and-test