version: 2.1
orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r test-requirements.txt
      - run:
          name: run tests
          command: pytest

workflows:
  main:
    jobs:
      - build-and-test