version: 2.1
orbs:
  python: circleci/python@2.1.1

jobs:
  build:
    executor: python/default
      steps:
        - checkout
        - run:
        name: Install dependencies
        command: pip install build
        - run:
            name: Build package
            command: python -m build
  publish:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install dependencies
          command: pip install twine
      - run:
          name: Publish
          command: python -m twine

workflows:
  main:
    jobs:
      - build
      - python/test:
          pip-dependency-file: test-requirements.txt
          pkg-manager: pip
          test-tool: pytest
      - publish:
        requires:
          - build
          - python/test