version: 2.1
orbs:
  python: circleci/python@2.1.1

jobs:
  build-and-test:
    executor: python/default
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest

workflows:
  main:
    jobs:
      - build-and-test