version: 2.1
orbs:
  python: circleci/python@2.1.1

jobs:
  build:
    executor: python/default
    working_directory: /tmp
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install build
      - run:
          name: Build package
          command: python -m build
#      - run:
#          name: Create build artifact
#          command: tar -czf dist.tar.gz -C ./dist .
      - store_artifacts:
          path: /tmp/dist
#          destination: dist.tar.gz

  publish-pypi:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install dependencies
          command: pip install twine
      - run:
          name: Publish
          command: python -m twine upload dist/*

workflows:
  main:
    jobs:
      - build
      - python/test:
          pip-dependency-file: test-requirements.txt
          pkg-manager: pip
          test-tool: pytest
      - publish-pypi:
          requires:
            - build
            - python/test