version: 2.1
orbs:
  python: circleci/python@2.1.1

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install build
      - run:
          name: Build package
          command: python -m build
      - store_artifacts:
          path: ./dist
      - run: mkdir -p workspace
      - run: mv dist workspace/.
      - persist_to_workspace:
          root: workspace
          paths:
            - dist

  publish-pypi:
    executor: python/default
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install dependencies
          command: pip install twine
      - run:
          name: List stuff
          command: echo `ls -lah`
      - run:
          name: Publish
          command: python -m twine upload workspace/dist/*

workflows:
  main:
    jobs:
      - build
      - python/test:
          pip-dependency-file: test-requirements.txt
          pkg-manager: pip
          test-tool: pytest
      - publish-pypi:
          requires:
            - build
            - python/test